// This file is automatically generated. Do not modify it manually.

const manifestVersion = "2.0.2"; // x-release-please-version

const manifest = JSON.parse(
  `
{
    "id": "ch.icorete.mattermost-timeline",
    "name": "Mattermost Timeline",
    "description": "Real-time animated timeline of events from external webhooks, displayed in the right-hand sidebar.",
    "homepage_url": "https://github.com/icoretech/mattermost-timeline",
    "support_url": "https://github.com/icoretech/mattermost-timeline/issues",
    "release_notes_url": "https://github.com/icoretech/mattermost-timeline/releases",
    "icon_path": "assets/icon.svg",
    "version": "__RELEASE_PLEASE_VERSION__",
    "min_server_version": "7.0.0",
    "server": {
        "executables": {
            "darwin-amd64": "server/dist/plugin-darwin-amd64",
            "darwin-arm64": "server/dist/plugin-darwin-arm64",
            "linux-amd64": "server/dist/plugin-linux-amd64",
            "linux-arm64": "server/dist/plugin-linux-arm64",
            "windows-amd64": "server/dist/plugin-windows-amd64.exe"
        },
        "executable": ""
    },
    "webapp": {
        "bundle_path": "webapp/dist/main.js"
    },
    "settings_schema": {
        "header": "",
        "footer": "",
        "settings": [
            {
                "key": "WebhookTokens",
                "display_name": "Webhook Tokens",
                "type": "custom",
                "help_text": "",
                "placeholder": "",
                "default": "[]",
                "hosting": "",
                "secret": true
            },
            {
                "key": "RequireSignedWebhooks",
                "display_name": "Require Signed Webhooks",
                "type": "custom",
                "help_text": "",
                "placeholder": "",
                "default": false,
                "hosting": "",
                "secret": false
            },
            {
                "key": "WebhookSecret",
                "display_name": "Webhook Secret (legacy)",
                "type": "custom",
                "help_text": "",
                "placeholder": "",
                "default": "",
                "hosting": "",
                "secret": true
            },
            {
                "key": "WebhookTools",
                "display_name": "Webhook URLs \u0026 Test",
                "type": "custom",
                "help_text": "",
                "placeholder": "",
                "default": "",
                "hosting": "",
                "secret": false
            },
            {
                "key": "MaxEventsStored",
                "display_name": "Maximum Events Stored",
                "type": "custom",
                "help_text": "",
                "placeholder": "",
                "default": "500",
                "hosting": "",
                "secret": false
            },
            {
                "key": "MaxEventsDisplayed",
                "display_name": "Maximum Events Displayed",
                "type": "custom",
                "help_text": "",
                "placeholder": "",
                "default": "100",
                "hosting": "",
                "secret": false
            },
            {
                "key": "TimelineOrder",
                "display_name": "Timeline Order",
                "type": "custom",
                "help_text": "",
                "placeholder": "",
                "default": "oldest_first",
                "hosting": "",
                "secret": false
            },
            {
                "key": "EnableReactions",
                "display_name": "Enable Reactions",
                "type": "custom",
                "help_text": "",
                "placeholder": "",
                "default": true,
                "hosting": "",
                "secret": false
            }
        ],
        "sections": null
    }
}
`.replace("__RELEASE_PLEASE_VERSION__", manifestVersion),
);

export default manifest;
