// This file is automatically generated. Do not modify it manually.

package main

import (
	"encoding/json"
	"strings"

	"github.com/mattermost/mattermost/server/public/model"
)

var manifest *model.Manifest

const manifestStr = `
{
  "id": "ch.icorete.mattermost-timeline",
  "name": "Mattermost Timeline",
  "description": "Real-time animated timeline of events from external webhooks, displayed in the right-hand sidebar.",
  "homepage_url": "https://github.com/icoretech/mattermost-timeline",
  "support_url": "https://github.com/icoretech/mattermost-timeline/issues",
  "release_notes_url": "https://github.com/icoretech/mattermost-timeline/releases",
  "icon_path": "assets/icon.svg",
  "version": "1.3.0",
  "min_server_version": "7.0.0",
  "server": {
    "executables": {
      "darwin-amd64": "server/dist/plugin-darwin-amd64",
      "darwin-arm64": "server/dist/plugin-darwin-arm64",
      "linux-amd64": "server/dist/plugin-linux-amd64",
      "linux-arm64": "server/dist/plugin-linux-arm64",
      "windows-amd64": "server/dist/plugin-windows-amd64.exe"
    },
    "executable": ""
  },
  "webapp": {
    "bundle_path": "webapp/dist/main.js"
  },
  "settings_schema": {
    "header": "Configure the Mattermost Timeline plugin.",
    "footer": "",
    "settings": [
      {
        "key": "WebhookSecret",
        "display_name": "Webhook Secret",
        "type": "text",
        "help_text": "Shared secret for authenticating incoming webhooks. External services must send this in the X-Webhook-Secret header.",
        "placeholder": "",
        "default": "",
        "hosting": "",
        "secret": true
      },
      {
        "key": "MaxEventsStored",
        "display_name": "Maximum Events Stored",
        "type": "text",
        "help_text": "Maximum number of events to persist per team. Oldest events are pruned when this limit is exceeded. Default: 500.",
        "placeholder": "",
        "default": "500",
        "hosting": "",
        "secret": false
      },
      {
        "key": "MaxEventsDisplayed",
        "display_name": "Maximum Events Displayed",
        "type": "text",
        "help_text": "Maximum number of events shown in the timeline at once. Default: 100.",
        "placeholder": "",
        "default": "100",
        "hosting": "",
        "secret": false
      },
      {
        "key": "TimelineOrder",
        "display_name": "Timeline Order",
        "type": "dropdown",
        "help_text": "Controls the display order of events in the timeline. Oldest-first shows newest events at the bottom; newest-first shows newest events at the top.",
        "placeholder": "",
        "default": "oldest_first",
        "options": [
          {
            "display_name": "Oldest first (newest at bottom)",
            "value": "oldest_first"
          },
          {
            "display_name": "Newest first (newest at top)",
            "value": "newest_first"
          }
        ],
        "hosting": "",
        "secret": false
      },
      {
        "key": "EnableReactions",
        "display_name": "Enable Reactions",
        "type": "bool",
        "help_text": "Allow users to react to timeline events with icon-based reactions.",
        "placeholder": "",
        "default": true,
        "hosting": "",
        "secret": false
      }
    ],
    "sections": null
  }
}
`

func init() {
	_ = json.NewDecoder(strings.NewReader(manifestStr)).Decode(&manifest)
}
