import type {EventEntry} from '../../webapp/src/types';

const now = Date.now();

export const FAKE_EVENTS: EventEntry[] = [
    {
        id: '1',
        team_id: 'team1',
        timestamp: now - 15_000,
        title: 'web-server-03 came online',
        message: 'Host recovered after **3 minutes** of downtime.\nAll health checks passing.',
        link: 'https://monitor.example.com/hosts/web-server-03',
        event_type: 'host_online',
        source: 'monitoring',
        client_reactions: {
            eyes: {count: 3, self: false, recent_users: ['user1', 'user2', 'user3']},
            check: {count: 1, self: true, recent_users: ['current-user']},
        },
    },
    {
        id: '2',
        team_id: 'team1',
        timestamp: now - 120_000,
        title: 'Deployed v2.4.1 to production',
        message: 'Commit `a1b2c3d` by @alice — *fixed login timeout issue*',
        links: [
            {url: 'https://github.com/example/app/releases/tag/v2.4.1', label: 'Release'},
            {url: 'https://github.com/example/app/actions/runs/99999', label: 'CI Run'},
            {url: 'https://grafana.example.com/d/deploy-metrics', label: 'Metrics'},
        ],
        event_type: 'deploy',
        source: 'ci/cd',
        channels: ['channel-dev', 'channel-ops'],
    },
    {
        id: '3',
        team_id: 'team1',
        timestamp: now - 300_000,
        title: 'High CPU alert on db-replica-02',
        message: 'CPU usage at **94%** for 5+ minutes.',
        links: [
            {url: 'https://grafana.example.com/d/cpu', label: 'Dashboard'},
            {url: 'https://pagerduty.example.com/incidents/P123', label: 'PagerDuty'},
        ],
        event_type: 'alert',
        source: 'alertmanager',
        channels: ['channel-dev', 'channel-ops'],
        client_reactions: {
            wrench: {count: 2, self: false, recent_users: ['user4', 'user5']},
            eyes: {count: 12, self: true, recent_users: ['user1', 'user2', 'current-user']},
        },
    },
    {
        id: '4',
        team_id: 'team1',
        timestamp: now - 600_000,
        title: 'web-server-03 went offline',
        message: 'Connection lost. Last heartbeat 10:42 AM.',
        event_type: 'host_offline',
        source: 'monitoring',
    },
    {
        id: '5',
        team_id: 'team1',
        timestamp: now - 900_000,
        title: 'SSL certificate renewed',
        message: 'Certificate for `*.example.com` renewed. Expires 2027-03-19.',
        event_type: 'success',
        source: 'certbot',
    },
    {
        id: '6',
        team_id: 'team1',
        timestamp: now - 1_800_000,
        title: 'Database migration completed',
        message: 'Migration `20260319_add_user_preferences` applied successfully to **production**.',
        links: [
            {url: 'https://github.com/example/app/pull/1234', label: 'PR'},
            {url: 'https://github.com/example/app/commit/f4e5d6', label: 'Commit'},
        ],
        event_type: 'info',
        source: 'migrations',
    },
    {
        id: '7',
        team_id: 'team1',
        timestamp: now - 3_600_000,
        title: 'Failed health check on api-gateway',
        message: 'Endpoint `/healthz` returned HTTP 503.\nRetrying in 30 seconds.',
        links: [
            {url: 'https://monitor.example.com/services/api-gateway', label: 'Service'},
            {url: 'https://logs.example.com/search?q=api-gateway', label: 'Logs'},
            {url: 'https://grafana.example.com/d/api-latency', label: 'Latency'},
            {url: 'https://pagerduty.example.com/incidents/P456', label: 'Incident'},
        ],
        event_type: 'error',
        source: 'monitoring',
    },
    {
        id: '8a',
        team_id: 'team1',
        timestamp: now - 5_400_000,
        title: 'Payment received: Invoice #2847',
        message: 'Customer **Acme Corp** paid `$12,500.00` for Q1 services.',
        links: [
            {url: 'https://stripe.com/payments/pi_abc123', label: 'Stripe'},
            {url: 'https://app.example.com/invoices/2847', label: 'Invoice'},
        ],
        event_type: 'money_in',
        source: 'billing',
    },
    {
        id: '8b',
        team_id: 'team1',
        timestamp: now - 6_600_000,
        title: 'Vendor payment sent: AWS',
        message: 'Monthly infrastructure bill: `$3,842.17`',
        links: [
            {url: 'https://console.aws.amazon.com/billing', label: 'AWS Billing'},
        ],
        event_type: 'money_out',
        source: 'accounting',
    },
    {
        id: '8',
        team_id: 'team1',
        timestamp: now - 7_200_000,
        title: 'Deployed v2.4.0 to staging',
        message: 'All **47 tests** passed. Ready for production review.',
        link: 'https://github.com/example/app/actions/runs/12345',
        event_type: 'deploy',
        source: 'ci/cd',
    },
    {
        id: '9',
        team_id: 'team1',
        timestamp: now - 10_800_000,
        title: 'New host provisioned: worker-node-05',
        message: 'Kubernetes node joined cluster. Resources: 16 vCPU, 64GB RAM.',
        event_type: 'host_online',
        source: 'terraform',
    },
    {
        id: '10',
        team_id: 'team1',
        timestamp: now - 14_400_000,
        title: 'Backup completed successfully',
        message: 'Full database backup: `db-prod-20260319.sql.gz` (2.3 GB)',
        event_type: 'generic',
        source: 'backup-service',
    },
    {
        id: '11',
        team_id: 'team1',
        timestamp: now - 180_000,
        title: 'Suspicious login attempt blocked',
        message: 'IP `203.0.113.42` failed 5 auth attempts for user **admin@example.com**.',
        links: [
            {url: 'https://auth0.example.com/logs/event/abc', label: 'Auth Log'},
        ],
        event_type: 'security',
        source: 'auth0',
    },
    {
        id: '12',
        team_id: 'team1',
        timestamp: now - 240_000,
        title: 'P1 Incident: API latency spike',
        message: 'p95 latency at **2.4s** (threshold: 500ms). On-call paged.',
        links: [
            {url: 'https://statuspage.example.com/incidents/inc-789', label: 'Statuspage'},
            {url: 'https://pagerduty.example.com/incidents/P789', label: 'PagerDuty'},
        ],
        event_type: 'incident',
        source: 'opsgenie',
        client_reactions: {
            megaphone: {count: 5, self: false, recent_users: ['user1', 'user2', 'user3']},
            hand: {count: 8, self: true, recent_users: ['user4', 'user5', 'current-user']},
            eyes: {count: 47, self: false, recent_users: ['user6', 'user7', 'user8']},
        },
    },
    {
        id: '13',
        team_id: 'team1',
        timestamp: now - 420_000,
        title: 'New team member: Sarah Chen',
        message: 'Joined the **Engineering** team as Senior Backend Developer.',
        event_type: 'user_joined',
        source: 'hr-system',
    },
    {
        id: '14',
        team_id: 'team1',
        timestamp: now - 480_000,
        title: 'Account deactivated: legacy-bot',
        message: 'Service account removed during quarterly access review.',
        event_type: 'user_left',
        source: 'identity',
    },
    {
        id: '15',
        team_id: 'team1',
        timestamp: now - 540_000,
        title: 'Scheduled maintenance: db-primary',
        message: 'Maintenance window `02:00–04:00 UTC` for index rebuild.',
        links: [
            {url: 'https://statuspage.example.com/maintenance/m-456', label: 'Status'},
        ],
        event_type: 'scheduled',
        source: 'ops-scheduler',
    },
    {
        id: '16',
        team_id: 'team1',
        timestamp: now - 60_000,
        title: 'PR #1892 approved',
        message: 'Reviewed by **@bob**: *LGTM, ship it!*',
        links: [
            {url: 'https://github.com/example/app/pull/1892', label: 'Pull Request'},
        ],
        event_type: 'review',
        source: 'github',
    },
    {
        id: '17',
        team_id: 'team1',
        timestamp: now - 30_000,
        title: 'Deploy notification sent',
        message: 'Notified **12 subscribers** about v2.4.1 release.',
        event_type: 'message',
        source: 'mailer',
    },
];

let nextId = 100;

const RANDOM_EVENTS = [
    {title: 'cache-server-01 came online', event_type: 'host_online', source: 'monitoring', message: 'Cache warmed up in **12 seconds**.'},
    {title: 'Deployed hotfix v2.4.2', event_type: 'deploy', source: 'ci/cd', message: 'Emergency fix for [#5678](https://github.com/example/app/issues/5678)', link: 'https://github.com/example/app/releases/tag/v2.4.2'},
    {title: 'Memory alert on web-server-01', event_type: 'alert', source: 'alertmanager', message: 'Memory usage at **91%**. Consider scaling.'},
    {title: 'load-balancer-02 went offline', event_type: 'host_offline', source: 'monitoring', message: 'Health check failed 3 consecutive times.'},
    {title: 'API rate limit hit', event_type: 'error', source: 'api-gateway', message: 'Client `mobile-app` exceeded 1000 req/min.'},
    {title: 'CDN cache purged', event_type: 'info', source: 'cloudflare', message: 'All static assets invalidated for `example.com`.'},
    {title: 'Scheduled maintenance starting', event_type: 'generic', source: 'ops-team', message: 'Database maintenance window: **30 minutes**.'},
    {title: 'DNS record updated', event_type: 'success', source: 'terraform', message: '`api.example.com` → `10.0.1.42`'},
];

export function generateRandomEvent(): EventEntry {
    const template = RANDOM_EVENTS[Math.floor(Math.random() * RANDOM_EVENTS.length)];
    return {
        id: String(nextId++),
        team_id: 'team1',
        timestamp: Date.now(),
        title: template.title,
        message: template.message,
        link: template.link,
        event_type: template.event_type,
        source: template.source,
    };
}
